apiVersion: v1
kind: Service
metadata:
  name: {{ include "bundle-analyzer.minioName" . }}
  labels:
    {{- include "bundle-analyzer.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: minio
    {{- include "bundle-analyzer.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
