apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bundle-analyzer.fullname" . }}-secret
  labels:
    {{- include "bundle-analyzer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "bundle-analyzer.databaseUrl" . | quote }}
  REDIS_URL: {{ include "bundle-analyzer.redisUrl" . | quote }}
  S3_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
  SECRET_KEY: {{ .Values.global.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.global.jwtSecretKey | quote }}
  BOOTSTRAP_ADMIN_EMAIL: {{ .Values.backend.bootstrapAdmin.email | quote }}
  BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.backend.bootstrapAdmin.password | quote }}
