{{- if and .Values.ingress.enabled .Values.ingress.generateSelfSignedCert }}
{{- $tlsName := printf "%s-tls" (include "bundle-analyzer.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $tlsName }}
{{- if or (not $existing) .Values.ingress.regenerateSelfSignedCert }}
{{- $host := (index .Values.ingress.hosts 0).host -}}
{{- $cert := genSelfSignedCert $host nil nil 365 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tlsName }}
  labels:
    {{- include "bundle-analyzer.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}
